### ISSUE TITLE
Questions on how to use custom objects

### ISSUE THREAD

**Issue by neixlo** [DLR-RM/RBGT#1]
Dear @manuel-stoiber and all who contributed to this repo,
thanks for making it available, seems to be another great work from DLR!

The paper isn't published yet if I got it right and I'm not familiar with C++. So I can't really dig into the repo myself.

I would like to use your repo to detect and track my own objects. So following questions came up:
1. Do I need to train/retrain to get the tracker working for my own objects? If so, how?
2. You're using .obj object files. Is the texture taken into account or can I convert my CAD files without texture into .obj files and use them?
3. Is there an initial detection step (for the first pose estimation) needed? If so, do I have to set/estimate it or is this also a part of this repo?
4. Will the paper or an upfront version appear before ACCV?

Thanks again to make your work public!

**Comment by manuel-stoiber** [comment]
Dear @neixlo,

thanks for your interest in our work. Here are the answers to your question:

1. No training in a deep-learning-sense is required. You need, however, to generate model files. As in 'examples/run_on_camera_sequence', you can do this using the following code:
'''
if (!body1_model_ptr->LoadModel(model_path, body1_model_name)) {
    body1_model_ptr->GenerateModel(*body1_ptr, 0.8f, 4, 200);
    body1_model_ptr->SaveModel(model_path, body1_model_name);
  }
'''
2. Texture is not taken into account. You can use .obj files without texture.
3. Pose detection is not part of the pipeline. Please use a detection pipeline of your choice.
4. Yes, we do plan to publish an upfront version in the coming week's. As soon as it is available, we will link it in the readme.

**Comment by neixlo** [comment]
Thanks.
