### ISSUE TITLE
about the rbot data

### ISSUE THREAD

**Issue by ghoshaw** [DLR-RM/RBGT#4]
Hi, could you release part of the rbot data, Like one object in your input format? The whole rbot data is too big to download.
Thanks!

**Comment by manuel-stoiber** [comment]
Hi @ghoshaw,
unfortunately, since we did not create the dataset, we will not release any of the RBOT data ourselves.
For questions regarding the dataset, we would like to refer you to its [creators](http://cvmr.info/research/RBOT/).
